cloud:
  aws:
    region:
      static: eu-central-1
      auto: false
      use-default-aws-region-chain: true
    stack:
      auto: false
    credentials:
      access-key: ${ADMIN_ACCESS_KEY}
      secret-key: ${ADMIN_SECRET_KEY}

queue:
  updates-messages-url: https://sqs.eu-central-1.amazonaws.com/999565175928/UpdatesMessagesQueue

sns:
  topic:
    updates-messages:
      arn: arn:aws:sns:eu-central-1:999565175928:UpdatesMessagesTopic